// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";

export type ApprovalResponse = { execution_process_id: string, status: ApprovalStatus, };
