// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberRole } from "./MemberRole";

export type CreateInvitationRequest = { email: string, role: MemberRole, };
