// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrganizationWithRole } from "./OrganizationWithRole";

export type CreateOrganizationResponse = { organization: OrganizationWithRole, };
