// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response wrapper for delete endpoints.
 */
export type DeleteResponse = { txid: bigint, };
