// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberRole } from "./MemberRole";

export type GetInvitationResponse = { id: string, organization_slug: string, role: MemberRole, expires_at: string, };
