// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HandoffInitRequest = { provider: string, return_to: string, app_challenge: string, };
