// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HandoffRedeemRequest = { handoff_id: string, app_code: string, app_verifier: string, };
