// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueCommentReaction = { id: string, comment_id: string, user_id: string, emoji: string, created_at: string, };
