// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueAssignee = { id: string, issue_id: string, user_id: string, assigned_at: string, };
