// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberRole } from "./MemberRole";

/**
 * Organization member info for API responses (without organization_id).
 * See also `OrganizationMember` in organization_member.rs for the full DB row type.
 */
export type OrganizationMemberInfo = { user_id: string, role: MemberRole, joined_at: string, };
